services:
  - type: web
    name: careerlens-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: CareerLensAI_SuperSecret_2024!xK9mP
      - key: JWT_SECRET_KEY
        value: CareerLensJWT_SecretKey_2024!zR7nQ
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGINS
        value: https://career-lens-ai-intelligent-resume-a.vercel.app
